const copy = {
  ar: { analyze:"حلّل", dashboard:"لوحة التحكم", eada:"منصة إعادة", eyebrow:"تحليل السكراب الذكي", title:'صوّر السكراب.<br><em>اكتشف قيمته.</em>', intro:"ارفع صورة وأدخل الوزن وحالة الفرز للحصول على تقدير أولي للمادة والنقاء والقيمة وأفضل مسار.", materials:"فئات مواد", routes:"مسارات قيمة", upload:"ارفع صورة السكراب", material:"نوع المادة", auto:"تقدير تلقائي", copper:"نحاس / كيابل", aluminum:"ألمنيوم", steel:"حديد / فولاذ", ewaste:"نفايات إلكترونية", battery:"بطاريات", mixed:"مختلط", weight:"الوزن (كجم)", clean:"حالة الفرز", sorted:"نظيف ومفروز", medium:"متوسط", dirty:"مختلط / ملوث", goal:"الهدف", sell:"بيع سريع", maximize:"تعظيم القيمة", export:"فرصة تصدير", recycle:"تدوير ملتزم", run:"تشغيل التحليل", disclaimer:"نموذج توضيحي وليس فحصًا مخبريًا أو عرض سعر ملزمًا.", waiting:"بانتظار بيانات السكراب", waitingText:"ستظهر هنا المادة والنقاء والقيمة والمسار المقترح.", f1:"صورة", f2:"تصنيف", f3:"نقاء", f4:"قيمة", f5:"مسار", overview:"سجل التحليلات والمسودات", analyses:"التحليلات", value:"القيمة المقدرة", listings:"مسودات العروض", recent:"آخر التحليلات", drafts:"مسودات العروض" },
  en: { analyze:"Analyze", dashboard:"Dashboard", eada:"EADA Platform", eyebrow:"Intelligent scrap analysis", title:'Photograph scrap.<br><em>Discover its value.</em>', intro:"Upload an image and enter weight and sorting condition for an indicative material, purity, value and route estimate.", materials:"Material classes", routes:"Value routes", upload:"Upload scrap image", material:"Material type", auto:"Auto estimate", copper:"Copper / cables", aluminum:"Aluminum", steel:"Iron / steel", ewaste:"E-waste", battery:"Batteries", mixed:"Mixed", weight:"Weight (kg)", clean:"Sorting condition", sorted:"Clean & sorted", medium:"Medium", dirty:"Mixed / contaminated", goal:"Goal", sell:"Sell fast", maximize:"Maximize value", export:"Export opportunity", recycle:"Compliant recycling", run:"Run analysis", disclaimer:"Demonstration model, not a laboratory inspection or binding quote.", waiting:"Waiting for scrap data", waitingText:"Material, purity, value and suggested route will appear here.", f1:"Image", f2:"Classify", f3:"Purity", f4:"Value", f5:"Route", overview:"Analysis and listing history", analyses:"Analyses", value:"Estimated value", listings:"Listing drafts", recent:"Recent analyses", drafts:"Listing drafts" }
};
const catalog = {
  copper:{ar:"نحاس / كيابل",en:"Copper / cables",price:27.5,purity:78,icon:"🟠"}, aluminum:{ar:"ألمنيوم",en:"Aluminum",price:7.2,purity:86,icon:"⚪"}, steel:{ar:"حديد / فولاذ",en:"Iron / steel",price:1.35,purity:92,icon:"⚙️"}, ewaste:{ar:"نفايات إلكترونية",en:"E-waste",price:9.8,purity:54,icon:"💻"}, battery:{ar:"بطاريات",en:"Batteries",price:3.9,purity:75,icon:"🔋"}, mixed:{ar:"سكراب مختلط",en:"Mixed scrap",price:4.2,purity:48,icon:"♻️"}
};
let lang = localStorage.getItem("scrap_ai_lang") || "ar";
function read(key,fallback){ try{return JSON.parse(localStorage.getItem(key)) ?? fallback}catch{return fallback} }
function applyLang(){ document.documentElement.lang=lang; document.documentElement.dir=lang==="ar"?"rtl":"ltr"; document.querySelectorAll("[data-t]").forEach(el=>{if(copy[lang][el.dataset.t])el.innerHTML=copy[lang][el.dataset.t]}); document.getElementById("langBtn").textContent=lang==="ar"?"EN":"AR"; renderDashboard() }
function toggleLang(){ lang=lang==="ar"?"en":"ar"; localStorage.setItem("scrap_ai_lang",lang); applyLang() }
function showPage(id){ document.querySelectorAll(".page").forEach(el=>el.classList.toggle("active",el.id===id)); if(id==="dashboard")renderDashboard(); scrollTo(0,0) }
function previewImage(event){ const file=event.target.files?.[0]; if(!file)return; if(!file.type.startsWith("image/")||file.size>8*1024*1024){toast(lang==="ar"?"اختر صورة أقل من 8 MB":"Choose an image under 8 MB");return} const reader=new FileReader(); reader.onload=e=>document.getElementById("preview").innerHTML=`<img src="${e.target.result}" alt="Scrap preview">`; reader.readAsDataURL(file) }
function inferMaterial(){ const selected=document.getElementById("material").value; if(selected!=="auto")return selected; const name=(document.getElementById("image").files?.[0]?.name||"").toLowerCase(); if(/copper|cable|wire/.test(name))return"copper"; if(/alum/.test(name))return"aluminum"; if(/steel|iron/.test(name))return"steel"; if(/battery|batt/.test(name))return"battery"; if(/pcb|electronic|laptop|phone/.test(name))return"ewaste"; return"mixed" }
function analyze(){
  const material=inferMaterial(), weight=Math.max(1,+document.getElementById("weight").value||1), clean=document.getElementById("clean").value, goal=document.getElementById("goal").value, item=catalog[material];
  const purity=Math.max(25,Math.min(98,item.purity+({clean:10,medium:0,dirty:-16}[clean]))), price=item.price*({clean:1.08,medium:.96,dirty:.78}[clean]), raw=Math.round(weight*price), cost=Math.round(weight*({clean:.15,medium:.65,dirty:1.35}[clean])), optimized=Math.round(raw*(clean==="clean"?1.03:clean==="medium"?1.14:1.24)-cost);
  let route="resale"; if(material==="mixed"||material==="battery"||clean==="dirty"||goal==="recycle")route="recycle"; if(goal==="export"&&clean!=="dirty")route="reexport"; if(goal==="maximize"&&clean!=="clean")route="upgrade";
  const routeName={ar:{resale:"بيع مباشر لمشترٍ صناعي",recycle:"تدوير عبر معالج مؤهل",reexport:"فحص فرصة إعادة تصدير",upgrade:"رفع درجة الفرز ثم البيع"},en:{resale:"Direct industrial sale",recycle:"Qualified recycling route",reexport:"Assess re-export opportunity",upgrade:"Improve grade, then sell"}}[lang][route], fmt=n=>n.toLocaleString(lang==="ar"?"ar-SA":"en-US"), name=item[lang];
  document.getElementById("result").innerHTML=`<div class="identify"><div><span class="material-chip">${item.icon} ${name}</span><p class="confidence">${lang==="ar"?"ثقة التقدير":"Estimate confidence"}: ${material==="mixed"?61:84}%</p></div></div><div class="metrics"><div class="metric"><span>${lang==="ar"?"النقاء":"Purity"}</span><strong>${purity}%</strong></div><div class="metric"><span>${lang==="ar"?"سعر / كجم":"Price / kg"}</span><strong>${fmt(price)} SAR</strong></div><div class="metric"><span>${lang==="ar"?"الوزن":"Weight"}</span><strong>${fmt(weight)} kg</strong></div></div><div class="recommend"><small>${lang==="ar"?"المسار المبدئي":"Preliminary route"}</small><h2>${routeName}</h2><p>${lang==="ar"?"يلزم فحص وعرض سعر حقيقي قبل التنفيذ.":"Inspection and a real quote are required before execution."}</p></div><div class="break"><div class="row"><span>${lang==="ar"?"القيمة الحالية":"Current value"}</span><strong>${fmt(raw)} SAR</strong></div><div class="row"><span>${lang==="ar"?"تكلفة التحسين":"Processing cost"}</span><strong>${fmt(cost)} SAR</strong></div><div class="row"><span>${lang==="ar"?"القيمة المحسنة":"Optimized value"}</span><strong>${fmt(optimized)} SAR</strong></div></div><div class="actions"><button class="auction" onclick="createListing('${material}',${weight},${optimized})">${lang==="ar"?"إنشاء مسودة عرض":"Create listing draft"}</button><button class="buyer" onclick="toast('${lang==="ar"?"مطابقة المشترين تتطلب قاعدة بيانات إنتاجية":"Buyer matching requires a production database"}')">${lang==="ar"?"مطابقة مشترٍ":"Match buyer"}</button></div>`;
  const history=read("scrap_ai_history",[]); history.unshift({material,weight,purity,value:optimized,route,date:new Date().toISOString()}); localStorage.setItem("scrap_ai_history",JSON.stringify(history.slice(0,50)));
}
function createListing(material,weight,value){ const listings=read("scrap_ai_listings",[]); listings.unshift({id:`SCRAP-${Date.now()}`,material,weight,value,status:"draft",date:new Date().toISOString()}); localStorage.setItem("scrap_ai_listings",JSON.stringify(listings)); toast(lang==="ar"?"تم إنشاء مسودة العرض":"Listing draft created") }
function renderDashboard(){ const history=read("scrap_ai_history",[]), listings=read("scrap_ai_listings",[]), fmt=n=>n.toLocaleString(lang==="ar"?"ar-SA":"en-US"); document.getElementById("statAnalyses").textContent=history.length; document.getElementById("statListings").textContent=listings.length; document.getElementById("statValue").textContent=`${fmt(history.reduce((sum,item)=>sum+item.value,0))} SAR`; document.getElementById("history").innerHTML=history.length?history.slice(0,10).map(item=>`<div class="history-item"><div><strong>${catalog[item.material]?.[lang]||item.material}</strong><small>${new Date(item.date).toLocaleDateString()}</small></div><strong>${fmt(item.value)} SAR</strong></div>`).join(""):`<p class="note">—</p>`; document.getElementById("listingList").innerHTML=listings.length?listings.slice(0,10).map(item=>`<div class="history-item"><div><strong>${item.id}</strong><small>${catalog[item.material]?.[lang]||item.material} · ${item.weight} kg</small></div><strong>${fmt(item.value)} SAR</strong></div>`).join(""):`<p class="note">—</p>` }
function toast(message){ const el=document.getElementById("toast"); el.textContent=message; el.style.display="block"; setTimeout(()=>el.style.display="none",2500) }
applyLang(); renderDashboard();
