(()=>{
const ar=document.documentElement.lang!=="en";
const t=(a,e)=>ar?a:e;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let user=null,data=null,platformData=null;
const style=document.createElement("style");style.textContent=`
#prodOpen{position:fixed;bottom:20px;inset-inline-end:20px;z-index:9998;border:0;border-radius:999px;padding:13px 18px;background:#0f6f57;color:#fff;font-weight:800}
#prodLayer{position:fixed;inset:0;background:#173b32aa;z-index:9999;display:none;place-items:center;padding:20px}
#prodLayer.open{display:grid}.prodCard{background:#fff;color:#16332b;border-radius:22px;width:min(980px,96vw);max-height:90vh;overflow:auto;padding:24px;box-shadow:0 30px 90px #0004}
.prodTop{display:flex;justify-content:space-between;gap:12px;align-items:center}.prodTop button{border:0;background:#eef7f3;border-radius:50%;width:38px;height:38px}
.prodGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.prodForm{display:grid;gap:12px;margin:18px 0}.prodField{display:grid;gap:6px}.prodField span{font-size:12px;font-weight:800;color:#49645b}.prodForm input,.prodForm select,.prodForm textarea{width:100%;box-sizing:border-box;padding:12px;border:1px solid #cad9d4;border-radius:10px;background:#fff;color:#16332b}.prodForm textarea{min-height:86px;resize:vertical}
.prodPrimary{border:0;border-radius:11px;padding:12px 16px;background:#0f6f57;color:#fff;font-weight:800}.prodSecondary{border:1px solid #9dbdb4;border-radius:11px;padding:10px;background:#fff;color:#173a34}.prodDanger{border:1px solid #e7b8b8;border-radius:11px;padding:10px;background:#fff7f7;color:#992d2d}
.prodItem{border:1px solid #dce8e4;border-radius:14px;padding:14px;background:#fff}.prodItem h4{margin:0 0 8px}.prodMuted{color:#62736e;font-size:13px}.prodError{color:#a42424;background:#fff0f0;padding:10px;border-radius:10px}.prodOk{color:#086b56;background:#eafff8;padding:10px;border-radius:10px}.prodRole{display:inline-flex;padding:5px 9px;border-radius:999px;background:#e8f7f0;color:#0f6f57;font-size:12px;font-weight:800}.prodSection{margin-top:24px}.prodSection>h3{margin-bottom:10px}.prodEmpty{padding:20px;border:1px dashed #c7dcd3;border-radius:14px;color:#6b7e77;text-align:center}
`;document.head.appendChild(style);

const open=document.createElement("button");open.id="prodOpen";open.textContent=t("حسابي","My account");document.body.appendChild(open);
const layer=document.createElement("div");layer.id="prodLayer";layer.innerHTML=`<section class="prodCard"><div class="prodTop"><div><b>${t("حساب Scrap AI","Scrap AI account")}</b><div class="prodMuted">${t("بيع وشراء حقيقي محفوظ في PostgreSQL","Real seller/buyer workflow stored in PostgreSQL")}</div></div><button id="prodClose" aria-label="Close">×</button></div><div id="prodBody"></div></section>`;document.body.appendChild(layer);
open.onclick=()=>{layer.classList.add("open");boot()};layer.querySelector("#prodClose").onclick=()=>layer.classList.remove("open");layer.onclick=e=>{if(e.target===layer)layer.classList.remove("open")};
const body=layer.querySelector("#prodBody");

async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...options});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"request_failed");return j}
function field(name,label,{type="text",value="",min="",required=true,placeholder="",options=null}={}){if(options)return `<label class="prodField"><span>${esc(label)}</span><select name="${name}" ${required?"required":""}>${options.map(o=>`<option value="${esc(o.value)}">${esc(o.label)}</option>`).join("")}</select></label>`;return `<label class="prodField"><span>${esc(label)}</span><input name="${name}" type="${type}" ${min!==""?`min="${min}"`:""} ${required?"required":""} value="${esc(value)}" placeholder="${esc(placeholder)}"></label>`}
function msg(value,ok=true){const host=body.querySelector("#prodMsg");if(host)host.innerHTML='<p class="'+(ok?"prodOk":"prodError")+'">'+esc(value)+'</p>'}

async function boot(){body.innerHTML="<p>"+t("جاري الاتصال...","Connecting...")+"</p>";try{const r=await api("/api/auth");user=r.user;if(user)await dashboard();else auth()}catch(e){body.innerHTML='<p class="prodError">'+esc(e.message)+'</p>'}}
function auth(){body.innerHTML=`<div class="prodGrid">
<form id="prodRegister" class="prodForm"><h3>${t("إنشاء حساب","Create account")}</h3>${field("fullName",t("الاسم","Name"))}${field("organizationName",t("المنشأة أو الاسم التجاري","Organization / business name"))}${field("kind",t("نوع الحساب","Account type"),{options:[{value:"seller",label:t("بائع","Seller")},{value:"buyer",label:t("مشتري","Buyer")},{value:"factory",label:t("مصنع / مشتري صناعي","Factory / industrial buyer")} ]})}${field("email",t("البريد الإلكتروني","Email"),{type:"email",placeholder:"email@example.com"})}${field("password",t("كلمة المرور","Password"),{type:"password"})}<button class="prodPrimary">${t("إنشاء الحساب","Create account")}</button></form>
<form id="prodLogin" class="prodForm"><h3>${t("تسجيل الدخول","Sign in")}</h3>${field("email",t("البريد الإلكتروني","Email"),{type:"email",placeholder:"email@example.com"})}${field("password",t("كلمة المرور","Password"),{type:"password"})}<button class="prodPrimary">${t("دخول","Sign in")}</button></form></div><div id="prodMsg"></div>`;
body.querySelector("#prodRegister").onsubmit=e=>authSubmit(e,"register");body.querySelector("#prodLogin").onsubmit=e=>authSubmit(e,"login")}
async function authSubmit(e,action){e.preventDefault();const fd=new FormData(e.target),payload=Object.fromEntries(fd);payload.action=action;const host=body.querySelector("#prodMsg");host.innerHTML=t("جاري الحفظ...","Saving...");try{const r=await api("/api/auth",{method:"POST",body:JSON.stringify(payload)});user=r.user;await dashboard()}catch(x){host.innerHTML='<p class="prodError">'+esc(x.message)+'</p>'}}

async function dashboard(){data=await api("/api/workflow");platformData=await api("/api/platform");body.innerHTML=`<div class="prodTop"><div><h3>${esc(user.organization_name)}</h3><div class="prodMuted">${esc(user.full_name)} · <span class="prodRole">${esc(user.kind)}</span></div></div><button id="prodLogout" class="prodSecondary">${t("خروج","Logout")}</button></div><div id="prodActions"></div><div id="prodData"></div><div id="prodMsg"></div>`;body.querySelector("#prodLogout").onclick=async()=>{await api("/api/auth",{method:"POST",body:JSON.stringify({action:"logout"})});user=null;auth()};render()}
function render(){renderScrap();renderOperations()}
async function refresh(okMessage){data=await api("/api/workflow");platformData=await api("/api/platform");if(okMessage)msg(okMessage);render()}
async function send(payload,success=t("تم حفظ العملية","Saved")){try{await api("/api/workflow",{method:"POST",body:JSON.stringify(payload)});await refresh(success)}catch(e){msg(e.message,false)}}
async function sendPlatform(payload,success=t("تم حفظ العملية","Operation saved")){try{await api("/api/platform",{method:"POST",body:JSON.stringify(payload)});await refresh(success)}catch(e){msg(e.message,false)}}
function inlineForm(title,fields,onSubmit,submitLabel=t("إرسال","Submit")){const host=body.querySelector("#prodMsg");host.innerHTML=`<form id="inlineAction" class="prodForm"><h4>${esc(title)}</h4><div class="prodGrid">${fields.map(f=>field(f.name,f.label,{type:f.type||"text",min:f.min??"",required:f.required!==false,placeholder:f.placeholder||""})).join("")}</div><button class="prodPrimary">${esc(submitLabel)}</button></form>`;host.querySelector("#inlineAction").onsubmit=e=>{e.preventDefault();onSubmit(Object.fromEntries(new FormData(e.target)))}}

function renderScrap(){
  const isSeller=["seller"].includes(user.kind);
  const isBuyer=["buyer","factory"].includes(user.kind);
  body.querySelector("#prodActions").innerHTML=isSeller?`<form id="mainForm" class="prodForm"><h3>${t("أضف بضاعة للبيع","List scrap for sale")}</h3><div class="prodGrid">
    ${field("title",t("عنوان العرض","Listing title"),{placeholder:t("مثال: كيابل نحاس مفروزة","e.g. Sorted copper cables")})}
    ${field("material",t("نوع المادة","Material"),{options:[{value:"copper",label:t("نحاس / كيابل","Copper / cables")},{value:"aluminum",label:t("ألمنيوم","Aluminum")},{value:"steel",label:t("حديد / فولاذ","Steel")},{value:"ewaste",label:t("إلكترونيات","E-waste")},{value:"battery",label:t("بطاريات","Batteries")},{value:"mixed",label:t("مختلط","Mixed scrap")} ]})}
    ${field("quantity",t("الكمية","Quantity"),{type:"number",min:"1"})}
    ${field("unit",t("الوحدة","Unit"),{options:[{value:"kg",label:t("كجم","kg")},{value:"ton",label:t("طن","ton")} ]})}
    ${field("city",t("المدينة","City"),{placeholder:t("الرياض","Riyadh")})}
    ${field("indicativeValue",t("السعر المطلوب / القيمة الإرشادية (ر.س)","Asking / indicative value (SAR)"),{type:"number",min:"0",required:false})}
  </div><div class="prodMuted">${t("بعد النشر تستطيع إضافة تحليل AI أو مستندات فحص من قسم التوثيق أدناه.","After publishing, you can add AI analysis or inspection evidence below.")}</div><button class="prodPrimary">${t("نشر العرض","Publish listing")}</button></form>`:`<div class="prodItem"><h3>${t("فرص الشراء","Buying opportunities")}</h3><p class="prodMuted">${t("اختر عرضاً مفتوحاً وقدّم السعر الذي يناسبك. لا يوجد شراء تلقائي أو خصم مالي بدون قبول البائع.","Choose an open listing and make an offer. No automatic purchase or payment occurs without seller acceptance.")}</p></div>`;
  if(isSeller) body.querySelector("#mainForm").onsubmit=e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.target));payload.quantity=Number(payload.quantity);payload.indicativeValue=payload.indicativeValue?Number(payload.indicativeValue):null;send({action:"createListing",...payload},t("تم نشر العرض","Listing published"))};

  const listingCards=data.listings.map(x=>`<article class="prodItem"><h4>${esc(x.title)}</h4><div class="prodMuted">${esc(x.material)} · ${esc(x.quantity)} ${esc(x.unit)} · ${esc(x.city)}</div><b>${esc(x.indicative_value||t("بدون سعر محدد","Price on request"))}${x.indicative_value?" SAR":""}</b><div class="prodMuted">${t("الحالة","Status")}: ${esc(x.status)}</div>${isBuyer&&x.seller_org_id!==user.organization_id&&x.status==="open"?'<button class="prodPrimary" data-offer="'+x.id+'">'+t("قدّم عرض شراء","Make purchase offer")+'</button>':""}</article>`).join("");
  const offerCards=data.offers.map(x=>`<article class="prodItem"><h4>${esc(x.title)}</h4><b>${esc(x.amount)} SAR</b><div class="prodMuted">${t("الحالة","Status")}: ${esc(x.status)}${x.buyer_name?` · ${esc(x.buyer_name)}`:""}</div>${isSeller&&x.seller_org_id===user.organization_id&&x.status==="submitted"?'<button class="prodPrimary" data-accept="'+x.id+'">'+t("قبول العرض وتحديد الاستلام","Accept & schedule pickup")+'</button>':""}</article>`).join("");
  body.querySelector("#prodData").innerHTML=`<section class="prodSection"><h3>${t("العروض المتاحة","Available listings")}</h3><div class="prodGrid">${listingCards||`<div class="prodEmpty">${t("لا توجد عروض حالياً","No listings yet")}</div>`}</div></section><section class="prodSection"><h3>${t("عروض الشراء","Purchase offers")}</h3><div class="prodGrid">${offerCards||`<div class="prodEmpty">${t("لا توجد عروض شراء بعد","No purchase offers yet")}</div>`}</div></section>`;
  body.querySelectorAll("[data-offer]").forEach(b=>b.onclick=()=>inlineForm(t("تقديم عرض شراء","Submit purchase offer"),[{name:"amount",type:"number",min:1,label:t("قيمة العرض بالريال","Offer amount in SAR")}],v=>send({action:"submitOffer",listingId:b.dataset.offer,amount:Number(v.amount)},t("تم إرسال عرض الشراء","Purchase offer sent")),t("إرسال العرض","Send offer")));
  body.querySelectorAll("[data-accept]").forEach(b=>b.onclick=()=>inlineForm(t("جدولة الاستلام","Schedule pickup"),[{name:"scheduledAt",type:"datetime-local",required:false,label:t("موعد الاستلام — اختياري","Pickup time — optional")},{name:"address",required:false,label:t("عنوان الاستلام — اختياري","Pickup address — optional")}],v=>send({action:"acceptOffer",offerId:b.dataset.accept,scheduledAt:v.scheduledAt||null,address:v.address||null},t("تم قبول العرض وإنشاء الاستلام","Offer accepted and pickup created")),t("قبول العرض","Accept offer")));
}

function renderOperations(){const host=body.querySelector("#prodData"),accepted=data.offers.filter(x=>x.status==="accepted"),tx=platformData?.transactions||[];host.insertAdjacentHTML("beforeend",`<section class="prodSection"><h3>${t("AI والتوثيق وإكمال الصفقة","AI, verification & deal completion")}</h3><div class="prodGrid">
<article class="prodItem"><h4>${t("توثيق الحساب","Account verification")}</h4><div class="prodMuted">${esc(platformData?.verification?.status||t("لم يقدم","Not submitted"))}</div><button class="prodSecondary" id="verifyOrg">${t("إرسال بيانات التوثيق","Submit verification")}</button></article>
<article class="prodItem"><h4>${t("صور وتقارير الفحص","Inspection photos & reports")}</h4><div class="prodMuted">${platformData?.storageConfigured?t("التخزين متصل","Storage connected"):t("رفع الملفات ينتظر إعداد R2","File upload needs R2 configuration")}</div><input id="scrapFile" type="file" accept="image/png,image/jpeg,image/webp,application/pdf"><button class="prodSecondary" id="uploadFile">${t("رفع مستند","Upload evidence")}</button></article>
<article class="prodItem"><h4>${t("تحليل صورة بالذكاء الاصطناعي","AI image analysis")}</h4><div class="prodMuted">${t("تحليل إرشادي يساعد في التصنيف والتوثيق؛ الفحص والوزن الفعليان يحسمان الصفقة.","Indicative analysis for classification and evidence; final inspection and weight determine the deal.")}</div><input id="scrapAiFile" type="file" accept="image/png,image/jpeg,image/webp"><input id="scrapAiCity" placeholder="${t("المدينة — اختياري","City — optional")}"><input id="scrapAiWeight" type="number" min="0" placeholder="${t("الوزن المتوقع كجم — اختياري","Estimated kg — optional")}"><button class="prodPrimary" id="analyzeScrap">${t("حلل الآن","Analyze now")}</button></article>
${accepted.map(o=>`<article class="prodItem"><h4>${esc(o.title)}</h4><div class="prodMuted">${t("عرض مقبول وجاهز لفتح معاملة الفحص والاستلام","Accepted offer ready for inspection/pickup transaction")}</div><button class="prodPrimary" data-create-tx="${o.id}">${t("ابدأ معاملة الاستلام","Start pickup transaction")}</button></article>`).join("")}
</div><div class="prodGrid">${tx.map(x=>`<article class="prodItem"><h4>${t("معاملة","Transaction")} ${esc(x.id.slice(0,8))}</h4><div class="prodMuted">${t("المرحلة","Stage")}: ${esc(x.stage)}</div><div>${esc(x.inspected_weight||x.estimated_weight||"-")} kg</div><button class="prodSecondary" data-inspect-tx="${x.id}">${t("تسجيل الفحص والوزن","Record inspection")}</button><button class="prodSecondary" data-advance-tx="${x.id}">${t("المرحلة التالية","Next stage")}</button><button class="prodDanger" data-dispute-tx="${x.id}">${t("فتح نزاع","Open dispute")}</button></article>`).join("")}</div></section>`);
  host.querySelector("#verifyOrg").onclick=()=>inlineForm(t("توثيق الحساب","Account verification"),[{name:"legalName",label:t("الاسم القانوني/الاسم الكامل","Legal/full name")},{name:"registrationNumber",label:t("السجل أو الهوية","CR or ID reference")},{name:"licenseNumber",required:false,label:t("ترخيص النشاط إن وجد","Activity license if applicable")}],v=>sendPlatform({action:"submitVerification",roleType:user.kind,...v},t("تم إرسال التوثيق للمراجعة","Verification submitted for review")));
  host.querySelectorAll("[data-create-tx]").forEach(b=>b.onclick=()=>sendPlatform({action:"createTransaction",offerId:b.dataset.createTx},t("تم فتح معاملة الاستلام","Pickup transaction started")));
  host.querySelectorAll("[data-inspect-tx]").forEach(b=>b.onclick=()=>inlineForm(t("نتيجة الفحص","Inspection result"),[{name:"inspectedWeight",type:"number",min:.01,label:t("الوزن الفعلي كجم","Actual weight kg")},{name:"purityPercent",type:"number",min:0,required:false,label:t("نسبة النقاوة — اختياري","Purity percent — optional")},{name:"weighbridgeTicket",required:false,label:t("رقم تذكرة الميزان — اختياري","Weighbridge ticket — optional")}],v=>sendPlatform({action:"recordInspection",transactionId:b.dataset.inspectTx,inspectedWeight:Number(v.inspectedWeight),purityPercent:v.purityPercent?Number(v.purityPercent):null,weighbridgeTicket:v.weighbridgeTicket||null},t("تم حفظ الفحص والوزن","Inspection and weight saved"))));
  host.querySelectorAll("[data-advance-tx]").forEach(b=>b.onclick=()=>sendPlatform({action:"advanceTransaction",transactionId:b.dataset.advanceTx}));
  host.querySelectorAll("[data-dispute-tx]").forEach(b=>b.onclick=()=>inlineForm(t("فتح نزاع","Open dispute"),[{name:"reason",label:t("السبب","Reason")},{name:"description",label:t("التفاصيل","Details")}],v=>sendPlatform({action:"openDispute",transactionId:b.dataset.disputeTx,...v})));
  host.querySelector("#uploadFile").onclick=uploadScrapFile;host.querySelector("#analyzeScrap").onclick=analyzeScrapFile;
}

async function uploadScrapFile(){const f=body.querySelector("#scrapFile")?.files?.[0];if(!f)return msg(t("اختر ملفاً","Choose a file"),false);try{const p=await api("/api/upload",{method:"POST",body:JSON.stringify({action:"presign",category:"inspection",fileName:f.name,contentType:f.type,sizeBytes:f.size})});const u=await fetch(p.uploadUrl,{method:"PUT",headers:p.headers,body:f});if(!u.ok)throw new Error("upload_failed");await api("/api/upload",{method:"POST",body:JSON.stringify({action:"complete",objectKey:p.objectKey,category:"inspection",fileName:f.name,contentType:f.type,sizeBytes:f.size})});await refresh(t("تم رفع الملف بشكل خاص","Private evidence uploaded"))}catch(e){msg(e.message,false)}}
function compactImage(file){return new Promise((resolve,reject)=>{if(!["image/jpeg","image/png","image/webp"].includes(file.type))return reject(new Error("invalid_image"));const reader=new FileReader();reader.onerror=()=>reject(new Error("image_read_failed"));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error("invalid_image"));img.onload=()=>{const scale=Math.min(1,1280/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.82))};img.src=reader.result};reader.readAsDataURL(file)})}
async function analyzeScrapFile(){const f=body.querySelector("#scrapAiFile")?.files?.[0];if(!f)return msg(t("اختر صورة للتحليل","Choose an image to analyze"),false);const button=body.querySelector("#analyzeScrap");button.disabled=true;button.textContent=t("جاري التحليل...","Analyzing...");try{const imageDataUrl=await compactImage(f),r=await api("/api/ai-analyze",{method:"POST",body:JSON.stringify({imageDataUrl,city:body.querySelector("#scrapAiCity")?.value,estimatedWeightKg:body.querySelector("#scrapAiWeight")?.value})}),a=r.analysis;body.querySelector("#prodMsg").innerHTML=`<article class="prodItem prodOk"><h4>${t("نتيجة AI الإرشادية","Indicative AI result")}</h4><p><b>${esc(ar?a.materialLabelAr:a.materialLabelEn)}</b> · ${esc(a.grade)} · ${Math.round(Number(a.confidence)*100)}%</p><p>${esc(ar?a.observationsAr:a.observationsEn)}</p><p><b>${t("الفحص المطلوب:","Required inspection:")}</b> ${esc(ar?a.recommendedInspectionAr:a.recommendedInspectionEn)}</p><p class="prodMuted">${esc(ar?a.pricingCaveatAr:a.pricingCaveatEn)}</p></article>`}catch(e){msg(e.message,false)}finally{button.disabled=false;button.textContent=t("حلل الآن","Analyze now")}}
})();
