(()=>{
const ar=()=>document.documentElement.lang!=="en";
const t=(a,e)=>ar()?a:e;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let user=null,data=null,platformData=null,mode="buy";

const style=document.createElement("style");style.textContent=`
#prodOpen{position:fixed;bottom:20px;inset-inline-end:20px;z-index:9998;border:0;border-radius:999px;padding:13px 18px;background:#0f6f57;color:#fff;font-weight:800}
#prodLayer{position:fixed;inset:0;background:#173b32aa;z-index:9999;display:none;place-items:center;padding:20px}
#prodLayer.open{display:grid}
#prodLayer.workspace{position:static;inset:auto;display:block;background:transparent;padding:0;z-index:1;place-items:stretch}
#prodLayer.workspace .prodCard{width:100%;max-height:none;box-shadow:none;padding:0;border-radius:0}
#prodLayer.workspace .prodClose{display:none}
.prodCard{background:#fff;color:#16332b;border-radius:22px;width:min(1000px,96vw);max-height:90vh;overflow:auto;padding:24px;box-shadow:0 30px 90px #0004}
.prodHeader{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;padding-bottom:16px;border-bottom:1px solid #dce8e4}.prodHeaderActions{display:flex;gap:8px;align-items:center}.prodClose{border:0;background:#eef7f3;border-radius:50%;width:40px;height:40px;font-size:20px}.prodLogout{border:1px solid #b7d3c8;background:#fff;color:#0f6f57;border-radius:10px;padding:9px 13px;font-weight:800}
.prodGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.prodForm{display:grid;gap:12px;margin:18px 0}.prodField{display:grid;gap:6px}.prodField span{font-size:12px;font-weight:800;color:#49645b}.prodForm input,.prodForm select,.prodForm textarea,.prodItem input{width:100%;box-sizing:border-box;padding:12px;border:1px solid #cad9d4;border-radius:10px;background:#fff;color:#16332b}.prodForm textarea{min-height:86px;resize:vertical}
.prodPrimary{border:0;border-radius:11px;padding:12px 16px;background:#0f6f57;color:#fff;font-weight:800}.prodSecondary{border:1px solid #9dbdb4;border-radius:11px;padding:10px;background:#fff;color:#173a34;font-weight:700}.prodDanger{border:1px solid #e7b8b8;border-radius:11px;padding:10px;background:#fff7f7;color:#992d2d}
.prodItem{border:1px solid #dce8e4;border-radius:14px;padding:14px;background:#fff}.prodItem h4{margin:0 0 8px}.prodMuted{color:#62736e;font-size:13px}.prodError{color:#a42424;background:#fff0f0;padding:10px;border-radius:10px}.prodOk{color:#086b56;background:#eafff8;padding:10px;border-radius:10px}.prodRole{display:inline-flex;padding:5px 9px;border-radius:999px;background:#e8f7f0;color:#0f6f57;font-size:12px;font-weight:800}.prodSection{margin-top:24px}.prodSection>h3{margin-bottom:10px}.prodEmpty{padding:20px;border:1px dashed #c7dcd3;border-radius:14px;color:#6b7e77;text-align:center}
.prodModeTabs{display:flex;gap:10px;margin:18px 0}.prodModeTabs button{flex:1;border:1px solid #b8d7ca;background:#fff;color:#0f6f57;border-radius:13px;padding:13px;font-weight:900}.prodModeTabs button.active{background:#0f6f57;color:#fff;border-color:#0f6f57}.prodModeHint{margin-top:-8px;color:#62736e;font-size:12px}
.prodPhoto{display:grid;gap:8px;padding:14px;border:1px dashed #b8d7ca;border-radius:14px;background:#f7fbf8}.prodPhoto img{max-height:160px;width:100%;object-fit:cover;border-radius:10px}
@media(max-width:640px){#prodLayer:not(.workspace){padding:8px}.prodCard{padding:16px;border-radius:16px}.prodHeader{align-items:center}.prodHeaderActions{flex-direction:column-reverse}.prodModeTabs{position:sticky;top:-16px;background:#fff;padding:10px 0;z-index:2}}
`;document.head.appendChild(style);

const workspace=document.getElementById("accountWorkspace");
const open=document.createElement("button");open.id="prodOpen";open.textContent=t("حسابي","My account");document.body.appendChild(open);
const layer=document.createElement("div");layer.id="prodLayer";layer.innerHTML=`<section class="prodCard"><div class="prodHeader"><div><b>${t("حساب سعودي سكراب","Saudi Scrap account")}</b><div class="prodMuted">${t("الحساب نفسه يستطيع البيع والشراء","The same account can buy and sell")}</div></div><div class="prodHeaderActions"><button id="prodClose" class="prodClose" aria-label="Close">×</button></div></div><div id="prodBody"></div></section>`;
if(workspace){layer.classList.add("workspace","open");workspace.appendChild(layer)}else document.body.appendChild(layer);
open.onclick=()=>openAccount();
layer.querySelector("#prodClose").onclick=()=>{if(typeof showPage==="function")showPage("home");else layer.classList.remove("open")};
if(!workspace)layer.onclick=e=>{if(e.target===layer)layer.classList.remove("open")};
const body=layer.querySelector("#prodBody");
function preferredMode(){const hinted=sessionStorage.getItem("scrap_ai_preferred_mode");if(hinted==="sell"||hinted==="buy"){sessionStorage.removeItem("scrap_ai_preferred_mode");return hinted}return null}
function openAccount(mode){if(mode==="sell"||mode==="buy")sessionStorage.setItem("scrap_ai_preferred_mode",mode);if(typeof showPage==="function"){showPage("account");return}layer.classList.add("open");boot()}

async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...options});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"request_failed");return j}
function field(name,label,{type="text",value="",min="",required=true,placeholder="",options=null}={}){if(options)return `<label class="prodField"><span>${esc(label)}</span><select name="${name}" ${required?"required":""}>${options.map(o=>`<option value="${esc(o.value)}" ${String(o.value)===String(value)?"selected":""}>${esc(o.label)}</option>`).join("")}</select></label>`;return `<label class="prodField"><span>${esc(label)}</span><input name="${name}" type="${type}" ${min!==""?`min="${min}"`:""} ${required?"required":""} value="${esc(value)}" placeholder="${esc(placeholder)}"></label>`}
function msg(value,ok=true){const host=body.querySelector("#prodMsg");if(host)host.innerHTML='<p class="'+(ok?"prodOk":"prodError")+'">'+esc(value)+'</p>'}

async function boot(){body.innerHTML=`<p>${t("جاري الاتصال...","Connecting...")}</p>`;try{const r=await api("/api/auth");user=r.user;if(user)await dashboard();else auth()}catch(e){body.innerHTML='<p class="prodError">'+esc(e.message)+'</p>'}}
function auth(){body.innerHTML=`<div class="prodGrid">
<form id="prodRegister" class="prodForm"><h3>${t("إنشاء حساب","Create account")}</h3>${field("fullName",t("الاسم","Name"))}${field("organizationName",t("المنشأة أو الاسم التجاري","Organization / business name"))}${field("kind",t("الشاشة المفضلة عند الدخول","Preferred starting view"),{options:[{value:"both",label:t("بائع ومشتري","Seller & buyer")},{value:"buyer",label:t("مشتري أولاً","Buyer first")},{value:"seller",label:t("بائع أولاً","Seller first")},{value:"factory",label:t("مشتري صناعي","Industrial buyer")} ]})}${field("email",t("البريد الإلكتروني","Email"),{type:"email",placeholder:"email@example.com"})}${field("password",t("كلمة المرور","Password"),{type:"password"})}<div class="prodMuted">${t("كل حساب يستطيع البيع والشراء؛ الاختيار يحدد شاشة البداية فقط.","Every account can buy and sell; this only selects the first screen.")}</div><button class="prodPrimary">${t("إنشاء الحساب","Create account")}</button></form>
<form id="prodLogin" class="prodForm"><h3>${t("تسجيل الدخول","Sign in")}</h3>${field("email",t("البريد الإلكتروني","Email"),{type:"email",placeholder:"email@example.com"})}${field("password",t("كلمة المرور","Password"),{type:"password"})}<button class="prodPrimary">${t("دخول","Sign in")}</button><button type="button" class="prodSecondary" id="forgotPassword">${t("نسيت كلمة المرور؟","Forgot password?")}</button></form></div><div id="prodMsg"></div>`;
body.querySelector("#prodRegister").onsubmit=e=>authSubmit(e,"register");body.querySelector("#prodLogin").onsubmit=e=>authSubmit(e,"login");body.querySelector("#forgotPassword").onclick=()=>msg(t("استرجاع كلمة المرور قيد الربط بالبريد الإلكتروني ولن نعرض زرًا وهميًا كحل نهائي.","Password recovery still needs the email delivery provider; it is not falsely marked as complete."),false)}
async function authSubmit(e,action){e.preventDefault();const payload=Object.fromEntries(new FormData(e.target));payload.action=action;const host=body.querySelector("#prodMsg");host.innerHTML=t("جاري الحفظ...","Saving...");try{const r=await api("/api/auth",{method:"POST",body:JSON.stringify(payload)});user=r.user;await dashboard()}catch(x){host.innerHTML='<p class="prodError">'+esc(x.message)+'</p>'}}

function initialMode(kind){return ["buyer","factory","both"].includes(kind)?"buy":"sell"}
function readListingDraft(){try{return JSON.parse(sessionStorage.getItem("scrap_ai_listing_draft")||"null")}catch{return null}}
function clearListingDraft(){sessionStorage.removeItem("scrap_ai_listing_draft")}
function mapMaterial(value){const v=String(value||"").toLowerCase();if(["mixed","copper","aluminum","steel","ewaste","battery"].includes(v))return v;if(/copper|كابل|نحاس/.test(v))return"copper";if(/alumin|ألمونيوم|المنيوم/.test(v))return"aluminum";if(/steel|iron|حديد|فولاذ/.test(v))return"steel";if(/e-?waste|electronic|إلكتر/.test(v))return"ewaste";if(/batter|بطار/.test(v))return"battery";return"mixed"}
async function dashboard(){data=await api("/api/workflow");platformData=await api("/api/platform");mode=readListingDraft()?"sell":(preferredMode()||initialMode(user.kind));body.innerHTML=`<div class="prodHeader"><div><h3 style="margin:0 0 5px">${esc(user.organization_name)}</h3><div class="prodMuted">${esc(user.full_name)} · <span class="prodRole">${t("بائع + مشتري","Seller + Buyer")}</span></div></div><div class="prodHeaderActions"><button id="prodLogout" class="prodLogout">${t("تسجيل الخروج","Logout")}</button></div></div><div class="prodModeTabs"><button id="prodBuyTab">🛒 ${t("أريد الشراء","I want to buy")}</button><button id="prodSellTab">📦 ${t("أريد البيع","I want to sell")}</button></div><div class="prodModeHint">${t("يمكنك التبديل بين الشراء والبيع في أي وقت بنفس الحساب.","Switch between buying and selling at any time with the same account.")}</div><div id="prodActions"></div><div id="prodData"></div><div id="prodMsg"></div>`;body.querySelector("#prodLogout").onclick=async()=>{await api("/api/auth",{method:"POST",body:JSON.stringify({action:"logout"})});user=null;auth()};body.querySelector("#prodBuyTab").onclick=()=>{mode="buy";render()};body.querySelector("#prodSellTab").onclick=()=>{mode="sell";render()};render()}
function render(){body.querySelector("#prodBuyTab")?.classList.toggle("active",mode==="buy");body.querySelector("#prodSellTab")?.classList.toggle("active",mode==="sell");renderMarket();renderOperations()}
async function refresh(okMessage){data=await api("/api/workflow");platformData=await api("/api/platform");render();if(okMessage)msg(okMessage)}
async function send(payload,success=t("تم حفظ العملية","Saved")){try{await api("/api/workflow",{method:"POST",body:JSON.stringify(payload)});await refresh(success)}catch(e){msg(e.message,false)}}
async function sendPlatform(payload,success=t("تم حفظ العملية","Operation saved")){try{await api("/api/platform",{method:"POST",body:JSON.stringify(payload)});await refresh(success)}catch(e){msg(e.message,false)}}
function inlineForm(title,fields,onSubmit,submitLabel=t("إرسال","Submit")){const host=body.querySelector("#prodMsg");host.innerHTML=`<form id="inlineAction" class="prodForm"><h4>${esc(title)}</h4><div class="prodGrid">${fields.map(f=>field(f.name,f.label,{type:f.type||"text",min:f.min??"",required:f.required!==false,placeholder:f.placeholder||""})).join("")}</div><button class="prodPrimary">${esc(submitLabel)}</button></form>`;host.querySelector("#inlineAction").onsubmit=e=>{e.preventDefault();onSubmit(Object.fromEntries(new FormData(e.target)))}}

function renderMarket(){const sell=mode==="sell",buy=mode==="buy";const draft=readListingDraft()||{};const materialOptions=[{value:"mixed",label:t("غير متأكد / مختلط","Not sure / mixed")},{value:"copper",label:t("نحاس / كيابل","Copper / cables")},{value:"aluminum",label:t("ألمنيوم","Aluminum")},{value:"steel",label:t("حديد / فولاذ","Steel")},{value:"ewaste",label:t("إلكترونيات","E-waste")},{value:"battery",label:t("بطاريات","Batteries")}];body.querySelector("#prodActions").innerHTML=sell?`<form id="mainForm" class="prodForm"><h3>${t("أضف بضاعة للبيع","List scrap for sale")}</h3><div class="prodMuted">${t("1) صورة  2) تحليل AI اختياري  3) تأكيد المدينة ونشر العرض. الوزن والسعر اختياريان.","1) Photo  2) Optional AI  3) Confirm city and publish. Weight and price are optional.")}</div><label class="prodPhoto"><span>${t("صورة السكراب","Scrap photo")}</span><input id="listingPhoto" type="file" accept="image/jpeg,image/png,image/webp"><img id="listingPreview" alt="" hidden><button type="button" class="prodSecondary" id="listingAnalyze">${t("حلّل الصورة بالذكاء الاصطناعي","Analyze photo with AI")}</button><div class="prodMuted" id="listingAiHint">${draft.analysisLabel?esc(draft.analysisLabel):t("AI يقترح المادة؛ أنت تؤكد قبل النشر. ليس سعرًا ملزمًا.","AI suggests the material; you confirm before publishing. It is not a binding price.")}</div></label><div class="prodGrid">${field("title",t("عنوان العرض","Listing title"),{value:draft.title||"",placeholder:t("مثال: أبواب حديد مستعملة","e.g. Used steel doors")})}${field("material",t("نوع المادة","Material"),{value:mapMaterial(draft.material),options:materialOptions})}${field("quantity",t("الكمية أو الوزن — اختياري","Quantity / weight — optional"),{type:"number",min:"0",required:false,value:draft.quantity||""})}${field("unit",t("الوحدة","Unit"),{options:[{value:"kg",label:t("كجم","kg")},{value:"ton",label:t("طن","ton")},{value:"piece",label:t("قطعة","piece")} ]})}${field("city",t("المدينة","City"),{value:draft.city||"",placeholder:t("الرياض","Riyadh")})}${field("district",t("الحي","District"),{placeholder:t("الروضة","Al Rawdah"),required:false})}${field("indicativeValue",t("السعر المطلوب — اختياري","Asking price — optional"),{type:"number",min:"0",required:false})}</div><button class="prodPrimary">${t("نشر العرض","Publish listing")}</button></form>`:`<div class="prodItem" id="buyerWelcome"><h3>${t("فرص الشراء","Buying opportunities")}</h3><p class="prodMuted">${t("أنت الآن في وضع المشتري. اختر فرصة وقدّم عرض شراء. اضغط «أريد البيع» فقط عندما تريد نشر بضاعة.","You are in buyer mode. Choose an opportunity and make an offer. Use “I want to sell” only when you want to list goods.")}</p></div>`;
if(sell){
  const photoInput=body.querySelector("#listingPhoto");
  const preview=body.querySelector("#listingPreview");
  photoInput.onchange=()=>{const file=photoInput.files?.[0];if(!file){preview.hidden=true;return}preview.src=URL.createObjectURL(file);preview.hidden=false};
  body.querySelector("#listingAnalyze").onclick=async()=>{const file=photoInput.files?.[0];if(!file)return msg(t("ارفع صورة أولاً","Upload a photo first"),false);try{const imageDataUrl=await compactImage(file);const r=await api("/api/ai-analyze",{method:"POST",body:JSON.stringify({imageDataUrl})});const a=r.analysis||{};const material=mapMaterial(a.materialType);const select=body.querySelector("[name=material]");if(select)select.value=material;const title=body.querySelector("[name=title]");if(title&&!title.value)title.value=ar()?a.materialLabelAr||"":a.materialLabelEn||"";body.querySelector("#listingAiHint").textContent=`${ar()?a.materialLabelAr:a.materialLabelEn} · ${a.grade||""} · ${t("تقديري — أكّد قبل النشر","indicative — confirm before publish")}`}catch(e){msg(e.message,false)}};
  body.querySelector("#mainForm").onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));p.quantity=p.quantity?Number(p.quantity):null;p.indicativeValue=p.indicativeValue?Number(p.indicativeValue):null;p.city=[p.city,p.district].filter(Boolean).join(" - ");delete p.district;try{const file=photoInput.files?.[0];if(file)p.imageUrl=await uploadListingPhoto(file);clearListingDraft();await send({action:"createListing",...p},t("تم نشر العرض","Listing published"));if(typeof loadLiveMarket==="function")loadLiveMarket()}catch(err){msg(err.message,false)}}
}
const listings=(data?.listings||[]).map(x=>`<article class="prodItem"><h4>${esc(x.title)}</h4><div class="prodMuted">${esc(x.material||t("غير محدد","Unspecified"))} · ${x.quantity?`${esc(x.quantity)} ${esc(x.unit||"")}`:t("الوزن غير معروف","Weight unknown")} · ${esc(x.city||"")}</div><b>${x.indicative_value?`${esc(x.indicative_value)} SAR`:t("السعر عند التفاوض","Price by negotiation")}</b><div class="prodMuted">${t("الحالة","Status")}: ${esc(x.status)}</div>${buy&&x.seller_org_id!==user.organization_id&&x.status==="open"?`<button class="prodPrimary" data-offer="${x.id}">${t("قدّم عرض شراء","Make purchase offer")}</button>`:""}</article>`).join("");
const offers=(data?.offers||[]).map(x=>`<article class="prodItem"><h4>${esc(x.title)}</h4><b>${esc(x.amount)} SAR</b><div class="prodMuted">${t("الحالة","Status")}: ${esc(x.status)}${x.buyer_name?` · ${esc(x.buyer_name)}`:""}</div>${sell&&x.seller_org_id===user.organization_id&&x.status==="submitted"?`<button class="prodPrimary" data-accept="${x.id}">${t("قبول العرض وتحديد الاستلام","Accept & schedule pickup")}</button>`:""}</article>`).join("");
body.querySelector("#prodData").innerHTML=`<section class="prodSection"><h3>${t("العروض المتاحة","Available listings")}</h3><div class="prodGrid">${listings||`<div class="prodEmpty">${t("لا توجد عروض حالياً","No listings yet")}</div>`}</div></section><section class="prodSection"><h3>${t("عروض الشراء","Purchase offers")}</h3><div class="prodGrid">${offers||`<div class="prodEmpty">${t("لا توجد عروض شراء بعد","No purchase offers yet")}</div>`}</div></section>`;
body.querySelectorAll("[data-offer]").forEach(b=>b.onclick=()=>inlineForm(t("تقديم عرض شراء","Submit purchase offer"),[{name:"amount",type:"number",min:1,label:t("قيمة العرض بالريال","Offer amount in SAR")}],v=>send({action:"submitOffer",listingId:b.dataset.offer,amount:Number(v.amount)},t("تم إرسال عرض الشراء","Purchase offer sent")),t("إرسال العرض","Send offer")));
body.querySelectorAll("[data-accept]").forEach(b=>b.onclick=()=>inlineForm(t("جدولة الاستلام","Schedule pickup"),[{name:"scheduledAt",type:"datetime-local",required:false,label:t("موعد الاستلام — اختياري","Pickup time — optional")},{name:"address",required:false,label:t("عنوان الاستلام — اختياري","Pickup address — optional")}],v=>send({action:"acceptOffer",offerId:b.dataset.accept,scheduledAt:v.scheduledAt||null,address:v.address||null},t("تم قبول العرض وإنشاء الاستلام","Offer accepted and pickup created")),t("قبول العرض","Accept offer")))}

function renderOperations(){const host=body.querySelector("#prodData"),accepted=(data?.offers||[]).filter(x=>x.status==="accepted"),tx=platformData?.transactions||[];host.insertAdjacentHTML("beforeend",`<section class="prodSection"><h3>${t("AI والتوثيق وإكمال الصفقة","AI, verification & deal completion")}</h3><div class="prodGrid"><article class="prodItem"><h4>${t("توثيق الحساب","Account verification")}</h4><div class="prodMuted">${esc(platformData?.verification?.status||t("لم يقدم","Not submitted"))}</div><button class="prodSecondary" id="verifyOrg">${t("إرسال بيانات التوثيق","Submit verification")}</button></article><article class="prodItem"><h4>${t("تحليل صورة بالذكاء الاصطناعي","AI image analysis")}</h4><div class="prodMuted">${t("تحليل محايد للطرفين؛ الوزن والسعر النهائيان يعتمدَان على الفحص الفعلي.","Neutral analysis for both parties; final weight and price depend on physical inspection.")}</div><input id="scrapAiFile" type="file" accept="image/png,image/jpeg,image/webp"><button class="prodPrimary" id="analyzeScrap">${t("حلل الصورة","Analyze image")}</button></article>${accepted.map(o=>`<article class="prodItem"><h4>${esc(o.title)}</h4><button class="prodPrimary" data-create-tx="${o.id}">${t("ابدأ معاملة الاستلام","Start pickup transaction")}</button></article>`).join("")}</div><div class="prodGrid">${tx.map(x=>`<article class="prodItem"><h4>${t("معاملة","Transaction")} ${esc(x.id.slice(0,8))}</h4><div class="prodMuted">${t("المرحلة","Stage")}: ${esc(x.stage)}</div><div>${esc(x.inspected_weight||x.estimated_weight||"-")} kg</div><button class="prodSecondary" data-inspect-tx="${x.id}">${t("تسجيل الفحص والوزن","Record inspection")}</button><button class="prodSecondary" data-advance-tx="${x.id}">${t("المرحلة التالية","Next stage")}</button></article>`).join("")}</div></section>`);
host.querySelector("#verifyOrg").onclick=()=>inlineForm(t("توثيق الحساب","Account verification"),[{name:"legalName",label:t("الاسم القانوني/الاسم الكامل","Legal/full name")},{name:"registrationNumber",label:t("السجل أو الهوية","CR or ID reference")}],v=>sendPlatform({action:"submitVerification",roleType:"buyer_seller",...v},t("تم إرسال التوثيق للمراجعة","Verification submitted")));
host.querySelectorAll("[data-create-tx]").forEach(b=>b.onclick=()=>sendPlatform({action:"createTransaction",offerId:b.dataset.createTx},t("تم فتح معاملة الاستلام","Pickup transaction started")));
host.querySelectorAll("[data-inspect-tx]").forEach(b=>b.onclick=()=>inlineForm(t("نتيجة الفحص","Inspection result"),[{name:"inspectedWeight",type:"number",min:.01,label:t("الوزن الفعلي كجم","Actual weight kg")},{name:"purityPercent",type:"number",min:0,required:false,label:t("نسبة النقاوة — اختياري","Purity — optional")}],v=>sendPlatform({action:"recordInspection",transactionId:b.dataset.inspectTx,inspectedWeight:Number(v.inspectedWeight),purityPercent:v.purityPercent?Number(v.purityPercent):null},t("تم حفظ الفحص والوزن","Inspection saved"))));
host.querySelectorAll("[data-advance-tx]").forEach(b=>b.onclick=()=>sendPlatform({action:"advanceTransaction",transactionId:b.dataset.advanceTx}));host.querySelector("#analyzeScrap").onclick=analyzeScrapFile}

function compactImage(file){return new Promise((resolve,reject)=>{if(!["image/jpeg","image/png","image/webp"].includes(file.type))return reject(new Error("invalid_image"));const reader=new FileReader();reader.onerror=()=>reject(new Error("image_read_failed"));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error("invalid_image"));img.onload=()=>{const scale=Math.min(1,1280/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.82))};img.src=reader.result};reader.readAsDataURL(file)})}
async function uploadListingPhoto(file){const imageDataUrl=await compactImage(file);try{const stored=await api("/api/upload",{method:"POST",body:JSON.stringify({action:"store",imageDataUrl,category:"listing",fileName:"listing.jpg",entityType:"scrap_listing"})});return stored.url||stored.objectKey}catch(error){if(String(error.message)==="object_storage_not_configured")return null;throw error}}
async function analyzeScrapFile(){const f=body.querySelector("#scrapAiFile")?.files?.[0];if(!f)return msg(t("اختر صورة للتحليل","Choose an image to analyze"),false);const button=body.querySelector("#analyzeScrap");button.disabled=true;button.textContent=t("جاري التحليل...","Analyzing...");try{const imageDataUrl=await compactImage(f),r=await api("/api/ai-analyze",{method:"POST",body:JSON.stringify({imageDataUrl})}),a=r.analysis;body.querySelector("#prodMsg").innerHTML=`<article class="prodItem prodOk"><h4>${t("نتيجة AI الإرشادية","Indicative AI result")}</h4><p><b>${esc(ar()?a.materialLabelAr:a.materialLabelEn)}</b> · ${esc(a.grade)} · ${Math.round(Number(a.confidence)*100)}%</p><p>${esc(ar()?a.observationsAr:a.observationsEn)}</p><p class="prodMuted">${esc(ar()?a.pricingCaveatAr:a.pricingCaveatEn)}</p></article>`}catch(e){msg(e.message,false)}finally{button.disabled=false;button.textContent=t("حلل الصورة","Analyze image")}}
window.openScrapSellDraft=function(draft){if(draft)sessionStorage.setItem("scrap_ai_listing_draft",JSON.stringify(draft));openAccount("sell")}
window.openScrapAccount=openAccount
window.bootScrapWorkspace=boot
if(document.getElementById("account")?.classList.contains("active")) boot()
})();
