import { access, readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
const files=["index.html","phase1.css","phase1.js","package.json","CHANGELOG.md","docs/TOP_5_PRODUCT_RESEARCH.md","docs/PRODUCT_BLUEPRINT.md","docs/FEATURE_GAP_MATRIX.md","docs/DEMO_LIMITATIONS.md","docs/LIVE_DEMO_TEST_REPORT.md"];
for(const file of files) await access(file);
const html=await readFile("index.html","utf8");
for(const marker of ['id="app"','id="toast"',"phase1.css","phase1.js"]) if(!html.includes(marker)) throw new Error(`Missing ${marker}`);
const source=await readFile("phase1.js","utf8");
for(const behavior of ["localStorage.scrap_phase1","function analyze","function publish","function offer","function accept","function advance","function resetDemo","seller","company","buyer","ops","admin"]) if(!source.includes(behavior)) throw new Error(`Missing behavior ${behavior}`);
const syntax=spawnSync(process.execPath,["--check","phase1.js"],{stdio:"inherit"});
if(syntax.status!==0) process.exit(syntax.status??1);
console.log("Scrap AI Phase 1 release checks passed.");
